// <auto-generated />
namespace Enchere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class champ_Maped_EnvoiDate_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(champ_Maped_EnvoiDate_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201805251507448_champ_Maped_EnvoiDate_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
